from . import account_report
from . import wizard_revenue_by_customer
from . import wizard_top_customers
from . import wizard_yearly_revenue_comparison
from . import wizard_quarterly_revenue_comparison
from . import wizard_revenue_by_customer_bu
from . import wizard_invoice_qty_by_bu
from . import wizard_invoice_list_report
from . import wizard_credit_note_list_report
from . import wizard_received_money_by_customer
from . import wizard_invoice_qty_by_customer
from . import wizard_receive_history_report
from . import wizard_ar_invoice_tracking_report
from . import wizard_ap_invoice_tracking_report
