from . import sale_team_performance_wizard
from . import sale_team_performance_detail_wizard
from . import st_perf_by_actual_qty_wizard
from . import st_perf_by_kpi_qty_wizard
from . import quotation_won_lost_wizard
from . import activity_n_productivity_wizard
from . import quotation_conversion_wizard
from . import qty_revised_quotation_wizard
from . import quotation_validity_wizard
from . import quotation_validity_details_wizard
from . import quotation_pipeline_wizard